### ISSUE TITLE
Missing cjs version of library

### ISSUE THREAD

**Issue by Gkleinereva** [words/stemmer#11]
## Issue
This library doesn't export a Common JS Package.  This would be convenient for most users of this library in a backend context, since typescript typically compiles to CommonJS for node applications (see https://www.typescriptlang.org/tsconfig#module).

While researching how to use this library in a NestJS context, I came across this article: https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1.  It has nice instructions for exporting both versions of a library without much work.

## Workaround
For now, I am using a deep import to import the library (e.g. `import { stemmer } from '../../../node_modules/stemmer/index';` instead of `import { stemmer } from 'stemmer';`.

**Comment by wooorm** [comment]
Hey! ESM is intentional.

You can configure TypeScript.

Dual doesn’t work well, particularly for projects that are deep down dependencies, such as this.

You can fine some more info here: https://github.com/search?o=desc&q=cjs+esm+user%3Awooorm+user%3Amdx-js+user%3Amicromark+user%3Aremarkjs+user%3Arehypejs+user%3Aretextjs+user%3Aunifiedjs+user%3Asyntax-tree+user%3Avfile+user%3Aget-alex+user%3Awords&s=created&type=issues.

**Comment by Gkleinereva** [comment]
Hey @wooorm thank you for looking into this and responding!  I'll look into an alternative typescript configuration, or just use the deep import for now.
